dist: xenial
sudo: required
language:
  - cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
    packages:
      - clang-8

before_install:
  - pip install --user cpp-coveralls

script:
  - export CXX="clang++-8" 
  - export CC="clang-8"
  - mkdir build
  - cd build
  - cmake -DVAJOLET_CPU_TYPE=64NEW -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - cd tests
  - ./Vajolet_unit_test
  - ./Vajolet_search_integration_test
  - cd ..
  - cd src
  - ./Vajolet bench
  - cd ..
  
after_success:
  - coveralls --gcov gcov-7 --root .. --gcov-options '\-lp' -e tests -e build/CMakeFiles -e build/googletest-src 
  
deploy:
  provider: releases
  api_key:
    secure: "2d44e875f1ce2fd6ea8eb9cf3026e9f5fbb196b2"
  file: "build/src/Vajolet"
  skip_cleanup: true
  draft: true
  