dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

before_install:
  - pip install --user cpp-coveralls

script:
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - mkdir build
  - cd build
  - cmake -DVAJOLET_CPU_TYPE=64NEW -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ./Vajolet_unit_test
  
after_success:
  - coveralls --gcov gcov-7 --root .. --gcov-options '\-lp'
  